const products = [
  {
    id: 1,
    name: "Apple iPad Air M3",
    category: "Electronics",
    image: "/images/products/ipad-front.png",
    hoverImage: "/images/products/ipad-back.png",
    price: 54999,
    oldPrice: 62999,
    discount: 13,
    review: 128,
    bestSeller: true,
  },

  {
    id: 2,
    name: "Premium Crepe T-Shirt",
    category: "Fashion",
    image: "/images/products/tshirt-front.png",
    hoverImage: "/images/products/tshirt-back.png",
    price: 899,
    oldPrice: 1299,
    discount: 31,
    review: 86,
    bestSeller: false,
  },

  {
    id: 3,
    name: "Leather Wrist Watch",
    category: "Fashion",
    image: "/images/products/watch-front.png",
    hoverImage: "/images/products/watch-back.png",
    price: 2499,
    oldPrice: 3499,
    discount: 29,
    review: 102,
    bestSeller: true,
  },

  {
    id: 4,
    name: "Diamond Ring",
    category: "Jewellery",
    image: "/images/products/ring-front.png",
    hoverImage: "/images/products/ring-back.png",
    price: 8999,
    oldPrice: 11999,
    discount: 25,
    review: 74,
    bestSeller: true,
  },

  {
    id: 5,
    name: "Modern Wooden Chair",
    category: "Furniture",
    image: "/images/products/chair-front.png",
    hoverImage: "/images/products/chair-back.png",
    price: 4999,
    oldPrice: 6499,
    discount: 23,
    review: 45,
    bestSeller: false,
  },

  {
    id: 6,
    name: "Running Sneakers",
    category: "Footwear",
    image: "/images/products/shoes-front.png",
    hoverImage: "/images/products/shoes-back.png",
    price: 2999,
    oldPrice: 3999,
    discount: 25,
    review: 138,
    bestSeller: true,
  },

  {
    id: 7,
    name: "Beauty Essentials Kit",
    category: "Beauty",
    image: "/images/products/beauty-1.png",
    hoverImage: "/images/products/beauty-2.png",
    price: 1499,
    oldPrice: 1999,
    discount: 25,
    review: 96,
    bestSeller: false,
  },

  {
    id: 8,
    name: "Fresh Grocery Pack",
    category: "Grocery",
    image: "/images/products/grocery-1.png",
    hoverImage: "/images/products/grocery-2.png",
    price: 699,
    oldPrice: 999,
    discount: 30,
    review: 57,
    bestSeller: false,
  },

  {
    id: 9,
    name: "Wireless Earbuds Pro",
    category: "Electronics",
    image: "/images/products/earbud-front.png",
    hoverImage: "/images/products/earbud-back.png",
    price: 1999,
    oldPrice: 2999,
    discount: 33,
    review: 210,
    bestSeller: true,
  },

  {
    id: 10,
    name: "Leather Handbag",
    category: "Fashion",
    image: "/images/products/bag-front.png",
    hoverImage: "/images/products/bag-back1.png",
    price: 3499,
    oldPrice: 4499,
    discount: 22,
    review: 69,
    bestSeller: false,
  },
];

export default products;